sudo: false
language: node_js
node_js:
  - "5"
install: gem install jekyll html-proofer jekyll-sitemap
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
script: npm run build:prod
deploy:
  skip_cleanup: true
  provider: script
  script: deploy.sh
  on:
    branch: master