sudo: false
language: node_js
node_js:
  - "5"
script: npm run build:prod
before_deploy: "mv dist wwwroot"
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master